config/routes.rb
Rails.application.routes.draw do

  root "events#index"

  resources :events do
    resources :registrations
  end

  resources :users
  get "signup" => "users#new"

  resource :session, only: [ :new, :create, :destroy ]
  get "signin" => "sessions#new"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :registrations, dependent: :destroy

  validates :name, :location, presence: true
  validates :description, length: { minimum: 25 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :capacity, numericality: { only_integer: true, greater_than: 0 }
  validates :image_file_name, format: {
    with: /\w+\.(jpg|png)\z/i,
    message: "Wrong file extension! Must be PNG or JPG!"
  }

  def free?
    price.to_f.zero? || price.blank? || price.nil?
  end

  def self.upcoming
    where("starts_at > ?", Time.now).order("starts_at")
  end

  def sold_out?
    (capacity - registrations.size).zero?
  end
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :event

  validates :name, presence: true
  validates :email, format: { with: /\S+@\S+/ }

  HOW_HEARD_OPTIONS = [
    "Newsletter",
    "Blog Post",
    "Twitter",
    "Web Search",
    "Friend/Coworker",
    "Other"
  ]
  validates :how_heard, inclusion: { in: HOW_HEARD_OPTIONS }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, format: { with: /\S+@\S+/ }, uniqueness: { case_sensitive: false }
  validates :username, presence: true,  format: { with: /\A[A-Z0-9]+\z/i }, uniqueness: { case_sensitive: false}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

private
  def current_user
    User.find_by(id: session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def require_signin
    unless current_user
      session[:intended_url] = request.url
      redirect_to new_session_url, alert: "Please, sign in first!"
    end
  end

  def current_user?(user)
    current_user == user
  end
  helper_method :current_user?
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.upcoming
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: "Updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event, notice: "New event was created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_path, status: :see_other
  end

  private
    def event_params
      params.require(:event).permit(:name, :description, :location, :price, :starts_at, :capacity, :image_file_name)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  before_action :set_event
  def index
    @registrations = @event.registrations
  end

  def new
    @registration = @event.registrations.new
  end

  def create
    @registration = @event.registrations.new(registration_params)

    if @registration.save
      redirect_to event_registrations_url(@event), notice: "You've registered to the event!"
    else
      render :new, status: :unprocessable_entity
    end
  end

private
  def registration_params
    params.require(:registration).permit(:name, :email, :how_heard)
  end

  def set_event
    @event = Event.find(params[:event_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to (session[:intended_url] || user),
                  notice: "Welcome back, #{user.name}"
      session[:intended_url] = nil
    else
      flash.now[:alert] = "Wrong username or password!"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to events_url, status: :see_other, notice: "Signed out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_signin, except: [ :new, :create ]
  before_action :require_correct_user, only: [ :edit, :update, :destroy ]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "User has been created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "Account details has been updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to events_url, status: :see_other, alert: "Account deleted!"
  end

private
  def user_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def require_correct_user
    @user = User.find(params[:id])
      redirect_to events_url, alert: "You can't do that with someone else!" unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def price event
    event.free? ? "Free" : number_to_currency(event.price)
  end

  def day_and_time(event)
    event.starts_at.strftime("%B %d at %I:%M %P")
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper

  def register_or_sold_out(event)
    if event.sold_out?
      content_tag(:span, "Sold Out", class: "sold-out")
    else
      link_to "Register", new_event_registration_path(event), class: "register"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event) do |f| %>

    <%= render "shared/errors", object: event %>

    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>

    <%= f.label :description %>
    <%= f.text_area :description, rows: 5 %>

    <%= f.label :location %>
    <%= f.text_field :location %>

    <%= f.label :price %>
    <%= f.number_field :price %>

    <%= f.label :starts_at %>
    <%= f.datetime_select :starts_at, {ampm: true}, {class: "datetime"} %>

    <%= f.label :capacity %>
    <%= f.number_field :capacity %>

    <%= f.label :image_file_name %>
    <%= f.text_field :image_file_name %>

    <%= f.submit %>
<% end %>

app/views/events/edit.html.erb
<h1><%= @event.name %></h1>

<%= render "form", event: @event %>

app/views/events/index.html.erb
<% @events.each do |event| %>
    <section class="event">
        <div class="image">
            <%= image_tag event.image_file_name %>
        </div>
        <div class="summary">
            <h2><%= link_to event.name, event %></h2>
            <h3><%= day_and_time(event) %> in <%= event.location %></h3>
            <span class="price">
                <%= price(event) %>
            </span>
            <p>
                <%= truncate(event.description, length: 35, separator: ' ') %>
            </p>
        </div>
    </section>
<% end %>

<section class="admin">
    <%= link_to "Add New Event", new_event_path, class: "button" %>
</section>

app/views/events/new.html.erb
<h1>Create a new Event</h1>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<section class="event-details">
    <div class="image">
        <%= image_tag @event.image_file_name %>
    </div>
    <div class="details">
        <h1> <%= @event.name %> </h1>
        <h2> <%= pluralize(@event.capacity, "spot") %> &bull; <%= price(@event) %> </h2>
        <h3>
            <%= day_and_time(@event) %> in <%= @event.location %>
        </h3>
        <p> <%= @event.description %> </p>
        <div class="register">
            <%= register_or_sold_out(@event) %>
            <p>
                <%= link_to ">> Wo's registered?", event_registrations_path(@event) %>
            </p>
        </div>
    </div>
</section>

<section class="admin">
    <%= link_to "Edit", edit_event_path(@event), class: "button" %>
    <%= link_to "Delete", @event, class: "button", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>

</section>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
    <div class="flash notice">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="flash alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
    <p>Made by Tachyon_Shift studio (c) 2025</p>
</footer>

app/views/layouts/_header.html.erb
<header>
    <nav>
    <%= link_to image_tag("logo.png"), root_path %>
    <ul class="left">
        <li>
        <%= link_to "All Events", events_path %>
        </li>
    </ul>
    <ul class="right">
        <%if current_user %>
            <li>
                <%= link_to current_user.name, current_user %>
            </li>
            <li>
                <%= link_to "Sign Out", session_path,
                    data: { turbo_method: :delete}, class: "button" %>
            </li>
        <% else %>
            <li>
                <%= link_to "Sign In", signin_path, class: "button" %>
            </li>
            <li>
                <%= link_to "Sign Up", signup_path, class: "button" %>
            </li>
        <% end %>
    </ul>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Eventz" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
    <%= render "layouts/header" %>

    <div class="content">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<section class="errors">
    <h2>
        Something went wrong!
    </h2>
    <h3>
        Please correct the following
        <%= pluralize(object.errors.size, "error") %>
    </h3>
    <ul>
        <% object.errors.full_messages.each do |message| %>
            <li>
                <%= message %>
            </li>
        <% end %>
    </ul>
</section>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |f| %>
    <%= render "shared/errors", object: user %>

    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>

    <%= f.label :username %>
    <%= f.text_field :username, placeholder: "Alphanumeric only" %>

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password%>

    <%= f.label :password_confirmation, "Confirm password" %>
    <%= f.password_field :password_confirmation %>

    <% if user.new_record?%>
        <%= f.submit "Create Account" %>
    <% else %>
        <%= f.submit "Update Account" %>
    <% end %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit <%= @user.name%> profile</h1>

<%= render "form", user: @user  %>

app/views/users/index.html.erb
<h1><%= pluralize(@users.size, "User")%></h1>
<ul class="users">
    <% @users.each do |u| %>
            <li>
                <%= link_to u.name, u %>
                created
                <%= time_ago_in_words(u.created_at) %> ago
            </li>
    <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<section class="user">
    <h1><%= @user.name %></h1>
    <h2>aka <%= @user.username%></h2>
    <h2><%= mail_to(@user.email) %></h2>
    <% if current_user?(@user) %>
        <div class="actions">
            <%= link_to "Edit Account", edit_user_path(@user), class: "button edit" %>
            <%= link_to "Delete Account", @user,
            data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "button delete" %>
        </div>
    <% end %>
</section>